### ISSUE TITLE
Tone down the font size on forum a bit

### ISSUE THREAD

**Issue by mrueschman** [nsrr/www.sleepdata.org#108]
I think we've discussed this and both agreed it may have gotten a bit too big.

**Comment by remomueller** [comment]
The font sizes are currently consistent across the site, toning these down would affect the documentation pages as well for datasets. I don't actually find these as too large currently on individual topics, but a bit large on the forum index. Thoughts?

**Comment by mrueschman** [comment]
So it's 24px currently? How about 18, which matches the font under the What / Who / When / Funded By stuff at the top?

Granted, this also makes the "Downloads" panel smaller, which makes the "Variables" panel unnecessarily large. I think we were contemplating changing that panel as well, though.
