### ISSUE TITLE
Create CSV export (and button) for DAUA agreements

### ISSUE THREAD

**Issue by mrueschman** [nsrr/www.sleepdata.org#109]
@remomueller suggested putting the button here: https://sleepdata.org/agreement_reports

@susansurovec requested:

> Also with regard to NSRR is there a way to access and download listings for DAUAs as in Slice?   I’d like to do some QA type review of dates, expirations, types of DAUA, etc and not sure of how to get access and/or download the data I want.  I’ve used the sorting available on the review and agreement screens but it doesn’t quite accomplish what I need.

**Comment by remomueller** [comment]
@mrueschman I'm closing this issue. We may want to add more to the export as time goes on, but we can create new issues if more is needed.

**Comment by susansurovec** [comment]
How can I  export data  from agreements – what fields are available to export to csv file?

**Comment by remomueller** [comment]
Hi @susansurovec, this is currently available on our staging server, and it allows you to download all fields that are collected during the DAUA process.

**Comment by susansurovec** [comment]
Actually was hoping for little more in the way of instructions of how to generate and download the csv file.   Available on our  staging server ?? … www.sleepdata.org<http://www.sleepdata.org>...  then ??

**Comment by remomueller** [comment]
Hi @susansurovec, I'll send you an example, these changes aren't live yet, it will be available directly from the admin panel for agreements (where you see them all listed) and say "CSV Export".
