### ISSUE TITLE
Update about page with metrics

### ISSUE THREAD

**Issue by remomueller** [nsrr/www.sleepdata.org#265]

**Comment by mrueschman** [comment]
If you become inspired, perhaps this will just become "Update about page". My cursory ideas on what to have:

- Quick description of site. "The National Sleep Research Resource (NSRR) is <a few words>."
- Some metrics, perhaps embedded into text would be simple enough. E.g. "**X** users have downloaded **Y TB** of data."
- Highlight funding source.

**Comment by remomueller** [comment]
These have been added to landing page, closing issue.
