### ISSUE TITLE
When signing-in to write a reply on long forum topic the header bar gets cleared

### ISSUE THREAD

**Issue by mrueschman** [nsrr/www.sleepdata.org#278]
E.g. start here: https://sleepdata.org/forum/about-the-variable-stonsetp-in-shhs

Scroll down and click "Write a Reply", header bar looks like this:

![image](https://cloud.githubusercontent.com/assets/707167/24613111/4929ab18-1855-11e7-9848-5576491ebfb1.png)

After signing in, header bar changes to this:

![image](https://cloud.githubusercontent.com/assets/707167/24613138/5f9e6f32-1855-11e7-9cd1-79acad252591.png)

Scrolling up and down doesn't change things - clever "jump to top" bit has disappeared forever (i.e. until next refresh)!

**Comment by remomueller** [comment]
Good catch, I should probably only be refreshing the right side of the navigation bar to fix this.
