### ISSUE TITLE
When browsing in files path, clicking on .MD file should display in web browser and not download

### ISSUE THREAD

**Issue by mrueschman** [nsrr/www.sleepdata.org#286]
![image](https://user-images.githubusercontent.com/707167/27435757-1a8c2f5a-572b-11e7-9ce4-535dfa409497.png)

If I click on "CHANGELOG.md" it should display in-line and not download the file. Most people would not know what to do with a .md file.

**Comment by remomueller** [comment]
Should we do the same with PDFs? (ie preview in browser?)

**Comment by mrueschman** [comment]
Sure, I'd like that (such as in the /documentation/ folders)
