### ISSUE TITLE
Coming soon month/year sometimes will exceed size of button

### ISSUE THREAD

**Issue by mrueschman** [nsrr/www.sleepdata.org#292]
E.g. 
<img width="553" alt="screen shot 2017-08-30 at 8 27 34 am" src="https://user-images.githubusercontent.com/707167/29872319-2c27791e-8d5d-11e7-80a3-29705fc3eb89.png">

**Comment by remomueller** [comment]
This has been fixed, the "fifth box" for seeing data access has been moved.

![screen shot 2017-11-08 at 7 31 04 pm](https://user-images.githubusercontent.com/316479/32582164-697309ce-c4bb-11e7-926d-f13562a28848.png)
