### ISSUE TITLE
Question regarding viewing "hidden" datasets with approved daua

### ISSUE THREAD

**Issue by remomueller** [nsrr/www.sleepdata.org#300]
Currently, users who have an approved DAUA for a dataset that has no public documentation, can't see that dataset on the datasets list. While this is an outlier (as most datasets are either "public" or "draft"), it looks at simplifying access to datasets. ie, only a DAUA grants viewership of draft datasets. Open for discussion, cc @mrueschman.

**Comment by mrueschman** [comment]
I'm all for simplifying, i.e. eliminating the sort of step that was needed today to add the user as a "viewer".

**Comment by remomueller** [comment]
Addressed in e862601aea3bfd8491e4f516c5f9ec03df60fb2c.
