### ISSUE TITLE
Add Dataset Infographic Overview

### ISSUE THREAD

**Issue by remomueller** [nsrr/www.sleepdata.org#32]
https://octoverse.github.com/

**Comment by remomueller** [comment]
Hi @mrueschman, I'm repurposing this issue to encapsulate the population, and other information you wanted to highlight per dataset. I think we could also include total download size (cache it on dataset model), type of population with some breakdowns.

Can you add to this issue the items you would like to see? Thanks!

**Comment by mrueschman** [comment]
Here are some ideas to start. I'd imagine these little meta-data fields would have some short taglines to on the dataset create/edit page to give a little guidanceof how to fill these in.

- [ ] What: One sentence summary of the study.
- [ ] Who: Description of the study population.
- [ ] When: Study timeframe.
- [ ] Funded by: List of funders / grant numbers.

Maybe "Citation" should also be an item? Not sure how these would be formatted if there were more than one (e.g. the study's primary paper and the NSRR paper -- or maybe the NSRR paper citation would be built in to all datasets).

Examples of some of the above info for SHHS and CHAT:

SHHS
 
What: Multi-cohort study focused on sleep-disordered breathing and cardiovascular outcomes
Who: 6,441 adults aged 40 and older
When: Two exam cycles, 1995-1998 and 2001-2003. Cardiovascular disease outcomes were tracked until 2010
Funder: National Heart, Lung, and Blood Institute
 
CHAT
 
What: Multi-center randomized trial comparing early adenotonsillectomy to watchful waiting plus supportive care
Who: 464 children aged 5-9.9 years with mild to moderate obstructive sleep apnea
When: 2007-2012, subjects had two visits – baseline and 7-month follow-up
Funder: National Heart, Lung, and Blood Institute
