### ISSUE TITLE
Identify common search terms

### ISSUE THREAD

**Issue by mrueschman** [nsrr/www.sleepdata.org#327]
Build a report that shows search terms/phrases and the frequency for NSRR search (don't track the user who submitted the search).

This could be useful to see what people are searching for and could inform future embellishments on the site (e.g. new variable labels to improve discoverability).

**Comment by remomueller** [comment]
Thanks, this should be similar to this: https://github.com/myapnea/www.myapnea.org/commit/dc161394f4a9c84f4058aa1521116554dfeac407#diff-f1d36687c4c649ebbb025139ed60ff37
