### ISSUE TITLE
Add additional reviewer choice "on the fence", or "need more information"

### ISSUE THREAD

**Issue by remomueller** [nsrr/www.sleepdata.org#74]
@mrueschman suggested that there be another option on the fence that reviewers could post for agreements that need slight revision. On resubmission, rejected and on the fence reviews would be cleared in order for reviewers to revisit the agreement.

**Comment by remomueller** [comment]
@mrueschman, revisiting this topic, now that we've gone through the review process, how do you feel about this issue?

**Comment by mrueschman** [comment]
Doesn't seem so important -- I just leave anything "on the fence" as unreviewed (typically with a comment to indicate I have reviewed it).

**Comment by remomueller** [comment]
Ok, closing this issue. Thanks! We can create a new issue in the future if the review process needs additional changes.
